jsxRuntime: automatic
typescript: true
icon: true
memo: true # TODO: remove after using React Compiler
filenameCase: kebab
outDir: src/icons
expandProps: end
svgProps:
  stroke: '{props.color || "currentColor"}'
  fill: none
  strokeLinecap: round
  strokeLinejoin: round
replaceAttrValues:
  '#000000': currentColor
  '#000': currentColor
